---
- name: ACM Tutorial Playbook
  hosts: apache

  vars:
    hostList: "{{ lookup('file', 'hostList.json') }}"
    tenant_id: "***"
    api_token: "***"
    oneagent_installer_script_url: "https://{{ tenant_id }}.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=***&arch=x86&flavor=default"
    defaultHostGroup: "DefaultGroup"

  tasks:
  - name: Check if Dynatrace OneAgent is already installed
    stat:
      path: /opt/dynatrace/oneagent/agent/lib64/liboneagentos.so
    register: agent_installed

  - name: Set Host Group Facts
    set_fact:
      hostGroup: "{{ item.hostGroup }}"
    loop: "{{ hostList }}"
    when: item.hostname == inventory_hostname

  - name: Download OneAgent
    get_url:
      url: "{{ oneagent_installer_script_url }}"
      dest: "/tmp/dynatrace-oneagent.sh"
    when: agent_installed.stat.exists == False

  - name: Install Agent
    shell: "sh /tmp/dynatrace-oneagent.sh --set-app-log-content-access=true --set-host-group={{ hostvars[inventory_hostname].hostGroup | default(defaultHostGroup)  }}"
    become: yes
    when: agent_installed.stat.exists == False

  - name: Get Current Host Group
    shell: "/opt/dynatrace/oneagent/agent/tools/lib64/oneagentutil --get-host-group"
    become: yes
    when: agent_installed.stat.exists == True
    register: currentHostGroup

  - name: Update Host Group
    shell: "/opt/dynatrace/oneagent/agent/tools/lib64/oneagentutil --set-host-group {{ hostvars[inventory_hostname].hostGroup | default(defaultHostGroup) }} --restart-service"
    become: yes
    when: agent_installed.stat.exists == True and currentHostGroup.stdout != (hostvars[inventory_hostname].hostGroup | default(defaultHostGroup))

  - name: "Set Facts"
    set_fact:
     "metadata" : "{{ item.metadata }}"
    loop: "{{ hostList }}"
    when: item.hostname == inventory_hostname

  - name: "Remove File if it Exists"
    become: yes
    file:
      path: /var/lib/dynatrace/oneagent/agent/config/hostcustomproperties.conf
      state: absent

  - name: "Write KVs to File"
    become: yes
    lineinfile:
      path: /var/lib/dynatrace/oneagent/agent/config/hostcustomproperties.conf
      line: "{{ item.key }}={{ item.value }}"
      create: yes
    with_dict: "{{ hostvars[inventory_hostname]['metadata'] }}"

  - name: Create ChargeCode Auto Tag Rule
    run_once: true
    uri:
      method: PUT
      status_code: 201, 204
      body_format: json
      url: https://{{ tenant_id }}.live.dynatrace.com/api/config/v1/autoTags/12345678-1234-1234-1234-123456789012?Api-Token={{ api_token }}
      body: |
        {
          "name": "ChargeCode",
          "rules": [
          {
            "type": "PROCESS_GROUP",
            "enabled": true,
            "valueFormat": "{Host:Environment:ChargeCode}",
            "propagationTypes": [
            "PROCESS_GROUP_TO_HOST",
            "PROCESS_GROUP_TO_SERVICE"
          ],
          "conditions": [
              {
              "key": {
                "attribute": "HOST_CUSTOM_METADATA",
                "dynamicKey": {
                  "source": "ENVIRONMENT",
                  "key": "ChargeCode"
                },
                "type": "HOST_CUSTOM_METADATA_KEY"
              },
              "comparisonInfo": {
                "type": "STRING",
                "operator": "EXISTS",
                "value": null,
                "negate": false,
                "caseSensitive": null
              }
            }
            ]
          }
        ]
        }

  - name: Create ConsumingRegion Auto Tag Rule
    run_once: true
    uri:
      method: PUT
      status_code: 201, 204
      body_format: json
      url: https://{{ tenant_id }}.live.dynatrace.com/api/config/v1/autoTags/23456789-2345-2345-2345-234567890123?Api-Token={{ api_token }}
      body: |
        {
          "name": "ConsumingRegion",
          "rules": [
          {
            "type": "PROCESS_GROUP",
            "enabled": true,
            "valueFormat": "{Host:Environment:ConsumingRegion}",
            "propagationTypes": [
            "PROCESS_GROUP_TO_HOST",
            "PROCESS_GROUP_TO_SERVICE"
          ],
          "conditions": [
              {
              "key": {
                "attribute": "HOST_CUSTOM_METADATA",
                "dynamicKey": {
                  "source": "ENVIRONMENT",
                  "key": "ConsumingRegion"
                },
                "type": "HOST_CUSTOM_METADATA_KEY"
              },
              "comparisonInfo": {
                "type": "STRING",
                "operator": "EXISTS",
                "value": null,
                "negate": false,
                "caseSensitive": null
              }
            }
            ]
          }
        ]
        }

  - name: Create Location Auto Tag Rule
    run_once: true
    uri:
      method: PUT
      status_code: 201, 204
      body_format: json
      url: https://{{ tenant_id }}.live.dynatrace.com/api/config/v1/autoTags/34567890-3456-3456-3456-345678901234?Api-Token={{ api_token }}
      body: |
        {
          "name": "Location",
          "rules": [
          {
            "type": "PROCESS_GROUP",
            "enabled": true,
            "valueFormat": "{Host:Environment:Location}",
            "propagationTypes": [
            "PROCESS_GROUP_TO_HOST",
            "PROCESS_GROUP_TO_SERVICE"
          ],
          "conditions": [
              {
              "key": {
                "attribute": "HOST_CUSTOM_METADATA",
                "dynamicKey": {
                  "source": "ENVIRONMENT",
                  "key": "Location"
                },
                "type": "HOST_CUSTOM_METADATA_KEY"
              },
              "comparisonInfo": {
                "type": "STRING",
                "operator": "EXISTS",
                "value": null,
                "negate": false,
                "caseSensitive": null
              }
            }
            ]
          }
        ]
        }
    
  - name: Create Owner Auto Tag Rule
    run_once: true
    uri:
      method: PUT
      status_code: 201, 204
      body_format: json
      url: https://{{ tenant_id }}.live.dynatrace.com/api/config/v1/autoTags/45678901-4567-4567-4567-456789012345?Api-Token={{ api_token }}
      body: |
        {
          "name": "Owner",
          "rules": [
          {
            "type": "PROCESS_GROUP",
            "enabled": true,
            "valueFormat": "{Host:Environment:Owner}",
            "propagationTypes": [
            "PROCESS_GROUP_TO_HOST",
            "PROCESS_GROUP_TO_SERVICE"
          ],
          "conditions": [
              {
              "key": {
                "attribute": "HOST_CUSTOM_METADATA",
                "dynamicKey": {
                  "source": "ENVIRONMENT",
                  "key": "Owner"
                },
                "type": "HOST_CUSTOM_METADATA_KEY"
              },
              "comparisonInfo": {
                "type": "STRING",
                "operator": "EXISTS",
                "value": null,
                "negate": false,
                "caseSensitive": null
              }
            }
            ]
          }
        ]
        }
