---
- name: Write vars
  hosts: local

  vars:
    hostList: "{{ lookup('file', 'customProperties.json') }}"

  tasks:

  - name: "Output all customProperties as-is"
    debug:
      msg: "{{ hostList }}"

  - name: "Print all hostnames"
    debug:
      msg: "{{ item.hostname }}"
    loop: "{{ hostList }}"
    
  - name: "Print 'foo2' for each host. Should be 'second' and 'fourth'."
    debug:
      msg: "{{ item.customProperties.foo2 }}"
    loop: "{{ hostList }}"

  - name: "Print 'foo' for host2. Should be 'third'."
    debug:
      msg: "{{ item.customProperties.foo }}"
    loop: "{{ hostList }}"
    when: "item.hostname == 'host2'"
