---
- name: Keptn Integration
  hosts: all
  
  tasks:
  
  - name: Debug
    ansible.builtin.debug:
      msg: "Hello World"
  
  #- name: Restart HTTPD
  #  service:
  #    name: httpd
  #    state: started
