---
- name: Keptn Integration
  hosts: all
  
  tasks:
 
  # Input for keptnTask is "{{ .type }}" coming from the Keptn webhook service
  # This comes in as "sh.keptn.event.taskname.triggered"
  # We only need the "taskname" and we add ".started" or ".finished" according to what we need
  - name: Split Task and Store Parts
    ansible.builtin.set_fact:
      task_parts: "{{ keptnTask.split('.') }}"
      
  - name: Print task
    ansible.builtin.debug:
      msg: "Task: {{ task_parts[3] }}"
      
  - name: Send Started Event to Keptn
    ansible.builtin.uri:
      url: "{{ keptnEndpoint }}/api/v1/event"
      method: POST
      body_format: json
      headers:
        Content-Type: application/json
        x-token: "{{ keptnAPIToken }}" # This should be encrypted and stored as a secret NEVER in plaintext
      body:
        data:
          project: "{{ keptnProject }}"
          service: "{{ keptnService }}"
          stage: "{{ keptnStage }}"
          status: "succeeded"
          result: "pass"
        source: "https://example.com/awx"
        specversion: "1.0"
        triggeredid: "{{ keptnTriggeredID }}"
        shkeptncontext: "{{ keptnContext }}"
        type: "sh.keptn.event.{{ task_parts[3] }}.started"
        
  - name: Doing real work here...
    ansible.builtin.pause:
      seconds: 5
      
  - name: Send Finished Event to Keptn
    ansible.builtin.uri:
      url: "{{ keptnEndpoint }}/api/v1/event"
      method: POST
      body_format: json
      headers:
        Content-Type: application/json
        x-token: "{{ keptnAPIToken }}" # This should be encrypted and stored as a secret NEVER in plaintext
      body:
        data:
          project: "{{ keptnProject }}"
          service: "{{ keptnService }}"
          stage: "{{ keptnStage }}"
          status: "succeeded"
          result: "pass"
        source: "https://example.com/awx"
        specversion: "1.0"
        triggeredid: "{{ keptnTriggeredID }}"
        shkeptncontext: "{{ keptnContext }}"
        type: "sh.keptn.event.{{ task_parts[3] }}.finished"
